### ISSUE TITLE
Invalid `pyproject.toml`

### ISSUE THREAD

**Issue by Viicos** [slaclab/lume-genesis#60]
Your `pyproject.toml` contains an invalid section:

https://github.com/slaclab/lume-genesis/blob/5e85e7f26b8d79f5f8840eccfd0ce727ffb78dd8/pyproject.toml#L46-L48

Instead, it should be:

```toml
[tool.setuptools] 
zip_safe = false 
include_package_data = true 
```

But note that `zip_safe` is deprecated and should probably be removed, and `include_package_data = true` is the default when using `pyproject.toml`, so all in all you can probably remove this completely.
